export { default as Login } from './Login/Login'

export { default as MainNav } from './Nav/MainNav/MainNav'

export { default as Hero } from './Hero/Hero'
export { default as Services } from './Services/Services'
export { default as ServiceBox } from './ServiceBox/SeriveBox'
export { default as SliderPartner } from './SliderPartner/SliderPartner'
export { default as Blog } from './Blog/Blog'
export { default as Mission } from './Mission/Mission'
export { default as Solution } from './Solution/Solution'
export { default as Footer } from './Footer/Footer'
export { default as WhyUs } from './WhyUs/WhyUs'
export { default as StrategicPartner } from './StrategicPartner/StrategicPartner'
export { default as SingleDoctor } from './SingleDoctor/SingleDoctor'
export { default as MyPlan } from './SinglePlan/MyPlan/MyPlan'
export { default as FamilyPlan } from './SinglePlan/FamilyPlan/FamilyPlanEnglish/FamilyPlan'
export { default as FamilyPlanMain } from './SinglePlan/FamilyPlan/FamilyPlanMain'
export { default as MyPlanB } from './SinglePlan/MyPlanB/MyPlanB'
export { default as Medicine } from './Medicine/Medicine'
export { default as Package } from './Package/Package'
export { default as AboutUs } from './AboutUs/AboutUs'
export { default as PlanSubscription } from './PlanSubscription/PlanSubscription'
export { default as TrainedAttendant } from './TrainedAttendant/TrainedAttendant'
export { default as Offer } from './Offer/Offer'
export { default as TeleHealth } from './Health/Health'

export { default as FindDoctors } from './FindDoctors/FindDoctors'
