export { default as MainNav } from './Nav/MainNav/MainNav'

export { default as Hero } from './Hero/Hero.jsx'
export { default as Services } from './Services/Services'
export { default as ServiceBox } from './ServiceBox/SeriveBox'
export { default as SliderPartner } from './SliderPartner/SliderPartner'
export { default as Blog } from './Blog/Blog'
export { default as Mission } from './Mission/Mission'
export { default as Solution } from './Solution/Solution'
export { default as Footer } from './Footer/Footer'
export { default as WhyUs } from './WhyUs/WhyUs'
export { default as StrategicPartner } from './StrategicPartner/StrategicPartner'
export { default as SingleDoctor } from './SingleDoctor/SingleDoctor'
export { default as MyPlan } from './SinglePlan/MyPlan/MyPlan'
export { default as FamilyPlan } from './SinglePlan/FamilyPlan/FamilyPlan'
