export { default as MainNav } from './Nav/MainNav/MainNav'
export { default as Hero } from './Hero/Hero'
export { default as Services } from './Services/Services'
export { default as ServiceBox } from './ServiceBox/SeriveBox'
export { default as SliderPartner } from './SliderPartner/SliderPartner'
export { default as Blog } from './Blog/Blog'
export { default as Footer } from './Footer/Footer'
export { default as WhyUs } from './WhyUs/WhyUs'
